/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * @param Number max
 * @returns Number
 */
const execute = max => {
    var sum = 0;
    var curr = 1;
    var next = 2;

    while (next < max) {
        next = curr + next;
        curr = next - curr;

        if (curr % 2 === 0) {
            sum = sum + curr;
        }
    }

    return sum;
};

test('test base case problem 2', () => {
    expect(execute(90)).toBe(44);
});

test('test use case problem 2', () => {
    expect(execute(4000000)).toBe(4613732);
});
